---
- hosts: localhost
  become: true

  vars:
    username: "vagrant"
    home: "/home/{{ username }}"
    document_root: "/{{ username }}"

  pre_tasks:
    - name: Install stuff from Aptitude
      apt: 
        name="{{ item }}"
        state=present
        update_cache=yes 
        cache_valid_time=86400
      with_items:
       - sudo
       - git
       - tig
       - gcc
       - gdb
       - cloc
       - bash-completion # Not included in the docker image
       - make
       - tree
       - htop
       - man-db
       - software-properties-common
       - libssl-dev # used by python2 for SSL checking
       - libffi-dev
       - python3-dev
       - python3-venv
       - python3-pip
       - iputils-ping
       - dnsutils
       - ripgrep

  roles:
    - zsh
    - neovim
    - python3.6
